Repository hassio-addons/addon-phpmyadmin, pull requests merged in 2022-01, with the labels that each got.

#118 ⬆️ Upgrades php8 to 8.0.14-r0
  phpmyadmin/Dockerfile
Labels: dependencies

#120 :fireworks: Updates maintenance/license year to 2022
  LICENSE.md
  README.md
  phpmyadmin/.README.j2
  phpmyadmin/DOCS.md
Labels: maintenance

#119 ⬆️ Upgrades add-on base image to 11.0.1
  phpmyadmin/Dockerfile
  phpmyadmin/build.yaml
Labels: dependencies

#117 🔨 Add Upload limit option
  phpmyadmin/DOCS.md
  phpmyadmin/config.yaml
  phpmyadmin/rootfs/etc/cont-init.d/nginx.sh
  phpmyadmin/rootfs/etc/nginx/includes/server_params.conf
  phpmyadmin/rootfs/etc/php8/conf.d/99-phpmyadmin.ini
  phpmyadmin/rootfs/etc/services.d/php-fpm/run
Labels: new-feature, dependencies
