Repository hassio-addons/addon-phpmyadmin, pull requests merged in 2023-03, with the labels that each got.

#149 ⬆️ Upgrades add-on base image to 13.1.3
  phpmyadmin/Dockerfile
  phpmyadmin/build.yaml
Labels: dependencies

#150 ⬆️ Upgrades phpMyAdmin to 5.2.1
  phpmyadmin/Dockerfile
Labels: dependencies

#151 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
Labels: maintenance

#155 Fix broken URL
  phpmyadmin/DOCS.md
Labels: documentation
